language: java
sudo: false
os:
 - linux
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - $HOME/.m2
install:
 - docker pull mongo

script:
- mvn -f pom.xml clean verify

env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start


notifications:
 email: false
 on_success: never
 on_failure: never
