dist: trusty
language: java

os:
 - linux
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "federicoguerri-github"
    token:
      secure: "77b4026d89a6e705fe586a12b1700d89b4e0c2e8"

services:
  - docker

cache:
  directories:
  - $HOME/.m2
  - '$HOME/.sonar/cache'

install:
 - docker pull mongo
 - docker pull redis

script:
- sleep 2
- mvn -f pom.xml clean verify
- sleep 2
- mvn -f pom.xml clean verify -Psecond-db
- mvn -f pom.xml verify -Pdocker-compose package sonar:sonar

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 

after_success:
- mvn clean test jacoco:report coveralls:report

notifications:
 email: false
 on_success: never
 on_failure: never
