language: java
os:
 - linux
jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    branches:
      - sonarcloud
      - master
    organization: "dani1993-github"
 
services:
  - docker

cache:
  directories:
  - $HOME/.m2
   - '$HOME/.sonar/cache'
   
install:
 - docker pull mongo
 
script:
- mvn -f pom.xml clean verify coveralls:report
- mvn -f pom.xml verify -Pdocker-compose

#env:
#  - DISPLAY=:99.0
#before_install:
#  - sh -e /etc/init.d/xvfb start
  
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

#before_install:
 #- sudo rm /etc/apt/sources.list.d/mongodb-3.2.list
 #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2048x2732x16"

after_success:
- mvn clean test jacoco:report coveralls:report

notifications:
 email: false
 on_success: never
 on_failure: never
