language: java
os:
 - linux
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - $HOME/.m2
install:
 - docker pull mongo

script:
- mvn -f pom.xml clean verify
- mvn -f pom.xml verify -Pdocker-compose

#env:
#  - DISPLAY=:99.0
#before_install:
#  - sh -e /etc/init.d/xvfb start
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
 - sudo rm /etc/apt/sources.list.d/mongodb-3.2.list


notifications:
 email: false
 on_success: never
 on_failure: never
