version: '2'

services:
  app:
    image: fatture-app
    links:
      - "db:mongo-host"
  db:
    image: mongo
    ports:
      - "27017:27017"
  redis:
  	image: "redis:alpine"
  	ports:
  	  - "6379"